//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceIssues
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Issue", Namespace="http://schemas.datacontract.org/2004/07/serviceIssues.Source.Model.WpfClient")]
    public partial class Issue : object
    {
        
        private string aktenzahlField;
        
        private string anmerkungField;
        
        private System.DateTime created_atField;
        
        private int creator_idField;
        
        private System.Nullable<System.DateTime> deadlineField;
        
        private System.Nullable<System.DateTime> endeField;
        
        private bool erledigtField;
        
        private bool gitField;
        
        private int idField;
        
        private int iidField;
        
        private string kundeField;
        
        private string mitarbeiterField;
        
        private System.Nullable<int> mitarbeiter_idField;
        
        private System.Nullable<int> prioPunkteField;
        
        private int project_idField;
        
        private System.Nullable<int> schaetzungField;
        
        private System.Nullable<int> schaetzungOffiziellField;
        
        private System.Nullable<int> sortOrderField;
        
        private System.Nullable<System.DateTime> startField;
        
        private int statusField;
        
        private string titelField;
        
        private int typField;
        
        private string web_urlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aktenzahl
        {
            get
            {
                return this.aktenzahlField;
            }
            set
            {
                this.aktenzahlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anmerkung
        {
            get
            {
                return this.anmerkungField;
            }
            set
            {
                this.anmerkungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime created_at
        {
            get
            {
                return this.created_atField;
            }
            set
            {
                this.created_atField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creator_id
        {
            get
            {
                return this.creator_idField;
            }
            set
            {
                this.creator_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> deadline
        {
            get
            {
                return this.deadlineField;
            }
            set
            {
                this.deadlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ende
        {
            get
            {
                return this.endeField;
            }
            set
            {
                this.endeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool erledigt
        {
            get
            {
                return this.erledigtField;
            }
            set
            {
                this.erledigtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool git
        {
            get
            {
                return this.gitField;
            }
            set
            {
                this.gitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iid
        {
            get
            {
                return this.iidField;
            }
            set
            {
                this.iidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kunde
        {
            get
            {
                return this.kundeField;
            }
            set
            {
                this.kundeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mitarbeiter
        {
            get
            {
                return this.mitarbeiterField;
            }
            set
            {
                this.mitarbeiterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> mitarbeiter_id
        {
            get
            {
                return this.mitarbeiter_idField;
            }
            set
            {
                this.mitarbeiter_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> prioPunkte
        {
            get
            {
                return this.prioPunkteField;
            }
            set
            {
                this.prioPunkteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int project_id
        {
            get
            {
                return this.project_idField;
            }
            set
            {
                this.project_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> schaetzung
        {
            get
            {
                return this.schaetzungField;
            }
            set
            {
                this.schaetzungField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> schaetzungOffiziell
        {
            get
            {
                return this.schaetzungOffiziellField;
            }
            set
            {
                this.schaetzungOffiziellField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> sortOrder
        {
            get
            {
                return this.sortOrderField;
            }
            set
            {
                this.sortOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titel
        {
            get
            {
                return this.titelField;
            }
            set
            {
                this.titelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int typ
        {
            get
            {
                return this.typField;
            }
            set
            {
                this.typField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string web_url
        {
            get
            {
                return this.web_urlField;
            }
            set
            {
                this.web_urlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mitarbeiter", Namespace="http://schemas.datacontract.org/2004/07/serviceIssues.Source.Model.WpfClient")]
    public partial class Mitarbeiter : object
    {
        
        private string avatar_urlField;
        
        private int dienstagField;
        
        private int donnerstagField;
        
        private int freitagField;
        
        private string gitTokenField;
        
        private string gitUsernameField;
        
        private int gitlab_idField;
        
        private int idField;
        
        private int mitarbeiterRoleField;
        
        private int mittwochField;
        
        private int montagField;
        
        private string nameField;
        
        private int team_idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string avatar_url
        {
            get
            {
                return this.avatar_urlField;
            }
            set
            {
                this.avatar_urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dienstag
        {
            get
            {
                return this.dienstagField;
            }
            set
            {
                this.dienstagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int donnerstag
        {
            get
            {
                return this.donnerstagField;
            }
            set
            {
                this.donnerstagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int freitag
        {
            get
            {
                return this.freitagField;
            }
            set
            {
                this.freitagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gitToken
        {
            get
            {
                return this.gitTokenField;
            }
            set
            {
                this.gitTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gitUsername
        {
            get
            {
                return this.gitUsernameField;
            }
            set
            {
                this.gitUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gitlab_id
        {
            get
            {
                return this.gitlab_idField;
            }
            set
            {
                this.gitlab_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mitarbeiterRole
        {
            get
            {
                return this.mitarbeiterRoleField;
            }
            set
            {
                this.mitarbeiterRoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mittwoch
        {
            get
            {
                return this.mittwochField;
            }
            set
            {
                this.mittwochField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int montag
        {
            get
            {
                return this.montagField;
            }
            set
            {
                this.montagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int team_id
        {
            get
            {
                return this.team_idField;
            }
            set
            {
                this.team_idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceIssues.IServiceIssue")]
    public interface IServiceIssue
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/getProjectIssues", ReplyAction="http://tempuri.org/IServiceIssue/getProjectIssuesResponse")]
        System.Threading.Tasks.Task<ServiceIssues.Issue[]> getProjectIssuesAsync(int project_id, int mitarbeiter_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/getProjectsIssues", ReplyAction="http://tempuri.org/IServiceIssue/getProjectsIssuesResponse")]
        System.Threading.Tasks.Task<ServiceIssues.Issue[]> getProjectsIssuesAsync(int[] projects_ids, int mitarbeiter_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/updateIssue", ReplyAction="http://tempuri.org/IServiceIssue/updateIssueResponse")]
        System.Threading.Tasks.Task<ServiceIssues.Issue> updateIssueAsync(ServiceIssues.Issue issue, int mitarbeiter_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/UpdateIssue20240401", ReplyAction="http://tempuri.org/IServiceIssue/UpdateIssue20240401Response")]
        System.Threading.Tasks.Task<ServiceIssues.Issue[]> UpdateIssue20240401Async(int[] projects_ids, int mitarbeiter_id, ServiceIssues.Issue modifiedIssue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/changeSortOrder", ReplyAction="http://tempuri.org/IServiceIssue/changeSortOrderResponse")]
        System.Threading.Tasks.Task<ServiceIssues.Issue[]> changeSortOrderAsync(int[] projects_ids, int mitarbeiter_id, int sortOrderFrom, int sortOrderTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/movePrioPunkte", ReplyAction="http://tempuri.org/IServiceIssue/movePrioPunkteResponse")]
        System.Threading.Tasks.Task<ServiceIssues.Issue[]> movePrioPunkteAsync(int id, bool isUpward);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/movePrioPunkteList", ReplyAction="http://tempuri.org/IServiceIssue/movePrioPunkteListResponse")]
        System.Threading.Tasks.Task<ServiceIssues.Issue[]> movePrioPunkteListAsync(int[] projects_ids, int[] ids, bool isUpward, int mitarbeiter_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/issuesAnordnen", ReplyAction="http://tempuri.org/IServiceIssue/issuesAnordnenResponse")]
        System.Threading.Tasks.Task issuesAnordnenAsync(System.Nullable<int> sortOrder, System.Nullable<int> mitarbeiter_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/getMitarbeiters", ReplyAction="http://tempuri.org/IServiceIssue/getMitarbeitersResponse")]
        System.Threading.Tasks.Task<ServiceIssues.Mitarbeiter[]> getMitarbeitersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIssue/getMitarbeiter", ReplyAction="http://tempuri.org/IServiceIssue/getMitarbeiterResponse")]
        System.Threading.Tasks.Task<ServiceIssues.Mitarbeiter> getMitarbeiterAsync(int mitarbeiter_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServiceIssueChannel : ServiceIssues.IServiceIssue, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceIssueClient : System.ServiceModel.ClientBase<ServiceIssues.IServiceIssue>, ServiceIssues.IServiceIssue
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceIssueClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceIssueClient.GetBindingForEndpoint(endpointConfiguration), ServiceIssueClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceIssueClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceIssueClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceIssueClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceIssueClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceIssueClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceIssues.Issue[]> getProjectIssuesAsync(int project_id, int mitarbeiter_id)
        {
            return base.Channel.getProjectIssuesAsync(project_id, mitarbeiter_id);
        }
        
        public System.Threading.Tasks.Task<ServiceIssues.Issue[]> getProjectsIssuesAsync(int[] projects_ids, int mitarbeiter_id)
        {
            return base.Channel.getProjectsIssuesAsync(projects_ids, mitarbeiter_id);
        }
        
        public System.Threading.Tasks.Task<ServiceIssues.Issue> updateIssueAsync(ServiceIssues.Issue issue, int mitarbeiter_id)
        {
            return base.Channel.updateIssueAsync(issue, mitarbeiter_id);
        }
        
        public System.Threading.Tasks.Task<ServiceIssues.Issue[]> UpdateIssue20240401Async(int[] projects_ids, int mitarbeiter_id, ServiceIssues.Issue modifiedIssue)
        {
            return base.Channel.UpdateIssue20240401Async(projects_ids, mitarbeiter_id, modifiedIssue);
        }
        
        public System.Threading.Tasks.Task<ServiceIssues.Issue[]> changeSortOrderAsync(int[] projects_ids, int mitarbeiter_id, int sortOrderFrom, int sortOrderTo)
        {
            return base.Channel.changeSortOrderAsync(projects_ids, mitarbeiter_id, sortOrderFrom, sortOrderTo);
        }
        
        public System.Threading.Tasks.Task<ServiceIssues.Issue[]> movePrioPunkteAsync(int id, bool isUpward)
        {
            return base.Channel.movePrioPunkteAsync(id, isUpward);
        }
        
        public System.Threading.Tasks.Task<ServiceIssues.Issue[]> movePrioPunkteListAsync(int[] projects_ids, int[] ids, bool isUpward, int mitarbeiter_id)
        {
            return base.Channel.movePrioPunkteListAsync(projects_ids, ids, isUpward, mitarbeiter_id);
        }
        
        public System.Threading.Tasks.Task issuesAnordnenAsync(System.Nullable<int> sortOrder, System.Nullable<int> mitarbeiter_id)
        {
            return base.Channel.issuesAnordnenAsync(sortOrder, mitarbeiter_id);
        }
        
        public System.Threading.Tasks.Task<ServiceIssues.Mitarbeiter[]> getMitarbeitersAsync()
        {
            return base.Channel.getMitarbeitersAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceIssues.Mitarbeiter> getMitarbeiterAsync(int mitarbeiter_id)
        {
            return base.Channel.getMitarbeiterAsync(mitarbeiter_id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceIssue))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IServiceIssue))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceIssue))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5010/ServiceIssue/basichttp");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IServiceIssue))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5011/ServiceIssue/WSHttps");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceIssue,
            
            WSHttpBinding_IServiceIssue,
        }
    }
}
