// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace libJxIssues.Models;

public class jxIssuesContext : DbContext
{
    public jxIssuesContext()
    {
    }
    public jxIssuesContext(DbContextOptions<jxIssuesContext> options)
        : base(options)
    {
    }
    public virtual DbSet<jxIssue> jxIssue { get; set; }
    public virtual DbSet<Mitarbeiter> mitarbeiter { get; set; }
    public virtual DbSet<ProgramInformation> programInformation { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        string server = @"PITWPROG19\SQLEXPRESS";
        string dataBase = "_jxIssues";
        string userId = "sysdba";
        string password = "masterkey";

        bool windowsAuthentication = false;

        string connectionString = $"Server={server};" +
                                  $"Database={dataBase};" +
                                  $"Trusted_Connection={windowsAuthentication};" +
                                  $"User Id={userId};" +
                                  $"Password={password};" +
                                  $"TrustServerCertificate=true;" +
                                  $"MultipleActiveResultSets=true;";

        optionsBuilder.UseSqlServer(connectionString);
    }
}